version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rebel_budget
      POSTGRES_USER: rebel_user
      POSTGRES_PASSWORD: rebel_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rebel_user -d rebel_budget"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Rebel Budget App (Frontend + Backend)
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://rebel_user:rebel_password@db:5432/rebel_budget
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - JWT_SECRET_KEY=your-jwt-secret-key-change-this-too
      - CORS_ORIGINS=http://localhost:8000
      - DEBUG=False
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # For development - mount source code
      - ./backend:/app
      - ./frontend/build:/app/static
    restart: unless-stopped

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  postgres_data:
  # redis_data: 